Primary:
  HAWKEYE_SNIPERRIFLE:
    Ammo: AMMO_SNIPER
    Amount: 16
  MOCKEYE_TESTRIFLE:
    Ammo: AMMO_SNIPER
    Amount: 16
  FIREFLY_SUBMACHINEGUN:
    Ammo: AMMO_SMG
    Amount: 4
  VULCAN_RIFLE:
    Ammo: AMMO_SNIPER
    Amount: 20
  DIABLE_FLAMETHROWER:
  TITAN_ASSAULTRIFLE:
    Ammo: AMMO_ASSAULTRIFLE
    Amount: 4
  ARES_ASSAULTRIFLE:
    Ammo: AMMO_ASSAULTRIFLE
    Amount: 4
  HADES_LIGHTMACHINEGUN:
    Ammo: AMMO_LMG
    Amount: 128
  PHOENIX_CARBINE:
    Ammo: AMMO_ASSAULTRIFLE
    Amount: 4